/*
* generated by Xtext
*/
package org.xconfig.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class XconfigOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
