/*
* generated by Xtext
*/
package org.xconfig.ui.contentassist;

import org.xconfig.ui.contentassist.AbstractXconfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XconfigProposalProvider extends AbstractXconfigProposalProvider {

}
