/*
* generated by Xtext
*/
package org.xconfig;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XconfigUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xconfig.ui.internal.XconfigActivator.getInstance().getInjector("org.xconfig.Xconfig");
	}
	
}
