/*
 * generated by Xtext
 */
package org.xconfig.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XconfigUiModule extends org.xconfig.ui.AbstractXconfigUiModule {
	public XconfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
