/*
 * generated by Xtext
 */
package org.xconfig.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xconfig.ui.internal.XconfigActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XconfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XconfigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XconfigActivator.getInstance().getInjector(XconfigActivator.ORG_XCONFIG_XCONFIG);
	}
	
}
