/*
 * generated by Xtext
 */
package org.xconfig;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XconfigRuntimeModule extends org.xconfig.AbstractXconfigRuntimeModule {

}
