/*
* generated by Xtext
*/
package org.xconfig.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xconfig.services.XconfigGrammarAccess;

public class XconfigParser extends AbstractContentAssistParser {
	
	@Inject
	private XconfigGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xconfig.ui.contentassist.antlr.internal.InternalXconfigParser createParser() {
		org.xconfig.ui.contentassist.antlr.internal.InternalXconfigParser result = new org.xconfig.ui.contentassist.antlr.internal.InternalXconfigParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getXmlConfigAccess().getGroup(), "rule__XmlConfig__Group__0");
					put(grammarAccess.getConfigElementAccess().getGroup(), "rule__ConfigElement__Group__0");
					put(grammarAccess.getModelAccess().getXmlsAssignment(), "rule__Model__XmlsAssignment");
					put(grammarAccess.getXmlConfigAccess().getNameAssignment_1(), "rule__XmlConfig__NameAssignment_1");
					put(grammarAccess.getXmlConfigAccess().getConfigElementsAssignment_3(), "rule__XmlConfig__ConfigElementsAssignment_3");
					put(grammarAccess.getConfigElementAccess().getNameAssignment_0(), "rule__ConfigElement__NameAssignment_0");
					put(grammarAccess.getConfigElementAccess().getTypeAssignment_2(), "rule__ConfigElement__TypeAssignment_2");
					put(grammarAccess.getConfigElementTypeAccess().getTypeAssignment(), "rule__ConfigElementType__TypeAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xconfig.ui.contentassist.antlr.internal.InternalXconfigParser typedParser = (org.xconfig.ui.contentassist.antlr.internal.InternalXconfigParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public XconfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XconfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
